"""Schema versions and JSON schemas for SQE outputs."""

from __future__ import annotations

from typing import Any, Dict

SCHEMA_VERSION = "1.1.0"

PROCESSED_SIGNAL_SCHEMA: Dict[str, Any] = {
    "$id": "https://schemas.sqe.local/processed_signal.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "ProcessedSignal",
    "type": "object",
    "required": [
        "signal_id",
        "timestamp",
        "raw",
        "filtered_ewma",
        "filtered_ma",
        "highpass",
        "drift",
        "drift_type",
        "drift_severity",
        "monotonic_samples",
        "variance",
        "std_dev",
        "noise_level",
        "is_spike",
        "spike_frequency",
        "oscillation_energy",
        "dominant_frequency",
        "sqi",
        "quality_class",
        "sqi_trend",
        "sqi_components",
        "sqi_weights",
        "stale",
        "stale_reason",
        "step_change",
        "step_offset",
        "plausibility_violation",
        "plausibility_reasons",
        "plausibility_rate",
        "alert_level",
        "drift_alert",
        "spike_alert",
    ],
    "properties": {
        "signal_id": {"type": "string"},
        "timestamp": {"type": "number"},
        "raw": {"type": "number"},
        "filtered_ewma": {"type": "number"},
        "filtered_ma": {"type": "number"},
        "highpass": {"type": "number"},
        "drift": {"type": "number"},
        "drift_type": {"type": "string"},
        "drift_severity": {"type": "number"},
        "monotonic_samples": {"type": "integer"},
        "variance": {"type": "number"},
        "std_dev": {"type": "number"},
        "noise_level": {"type": "number"},
        "is_spike": {"type": "boolean"},
        "spike_frequency": {"type": "number"},
        "oscillation_energy": {"type": "number"},
        "dominant_frequency": {"type": ["number", "null"]},
        "sqi": {"type": "number"},
        "quality_class": {"type": "string"},
        "sqi_trend": {"type": "string"},
        "sqi_components": {"type": "object"},
        "sqi_weights": {"type": "object"},
        "stale": {"type": "boolean"},
        "stale_reason": {"type": ["string", "null"]},
        "step_change": {"type": "boolean"},
        "step_offset": {"type": ["number", "null"]},
        "plausibility_violation": {"type": "boolean"},
        "plausibility_reasons": {"type": "array", "items": {"type": "string"}},
        "plausibility_rate": {"type": ["number", "null"]},
        "alert_level": {"type": "string"},
        "drift_alert": {"type": "boolean"},
        "spike_alert": {"type": "boolean"},
    },
}

PROCESSED_SCAN_SCHEMA: Dict[str, Any] = {
    "$id": "https://schemas.sqe.local/processed_scan.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "ProcessedScan",
    "type": "object",
    "required": ["schema_version", "scan_timestamp", "processed_signals"],
    "properties": {
        "schema_version": {"type": "string"},
        "scan_timestamp": {"type": "number"},
        "processed_signals": {
            "type": "object",
            "additionalProperties": PROCESSED_SIGNAL_SCHEMA,
        },
        "suppression_stats": {"type": ["object", "null"]},
    },
}

PROCESSED_SCAN_ROW_SCHEMA: Dict[str, Any] = {
    "$id": "https://schemas.sqe.local/processed_scan_row.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "ProcessedScanRow",
    "type": "object",
    "required": [
        "schema_version",
        "scan_timestamp",
        "signal_id",
        "timestamp",
        "sqi",
        "quality_class",
        "dominant_cause",
        "severity",
        "components",
        "alert_level",
        "drift_alert",
        "spike_alert",
    ],
    "properties": {
        "schema_version": {"type": "string"},
        "scan_timestamp": {"type": "number"},
        "signal_id": {"type": "string"},
        "timestamp": {"type": "number"},
        "sqi": {"type": "number"},
        "quality_class": {"type": "string"},
        "dominant_cause": {"type": "string"},
        "severity": {"type": "string"},
        "components": {"type": "object"},
        "alert_level": {"type": "string"},
        "drift_alert": {"type": "boolean"},
        "spike_alert": {"type": "boolean"},
        "suppression_stats": {"type": "object"},
    },
}

INCIDENT_EVENT_SCHEMA: Dict[str, Any] = {
    "$id": "https://schemas.sqe.local/incident_event.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "IncidentEvent",
    "type": "object",
    "required": ["schema_version", "event_type", "message", "recommended_action"],
    "properties": {
        "schema_version": {"type": "string"},
        "event_type": {"type": "string"},
        "message": {"type": "string"},
        "recommended_action": {"type": "string"},
        "incident": {
            "type": "object",
            "required": [
                "incident_id",
                "signal_id",
                "cause",
                "severity",
                "start_timestamp",
                "last_timestamp",
                "end_timestamp",
                "min_sqi",
                "last_sqi",
                "start_scan_index",
                "last_scan_index",
                "details",
            ],
            "properties": {
                "incident_id": {"type": "string"},
                "signal_id": {"type": "string"},
                "cause": {"type": "string"},
                "severity": {"type": "string"},
                "start_timestamp": {"type": "number"},
                "last_timestamp": {"type": "number"},
                "end_timestamp": {"type": ["number", "null"]},
                "min_sqi": {"type": "number"},
                "last_sqi": {"type": "number"},
                "start_scan_index": {"type": "integer"},
                "last_scan_index": {"type": "integer"},
                "details": {"type": "object"},
            },
        },
    },
}

GROUP_INCIDENT_EVENT_SCHEMA: Dict[str, Any] = {
    "$id": "https://schemas.sqe.local/group_incident_event.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "GroupIncidentEvent",
    "type": "object",
    "required": [
        "schema_version",
        "group_id",
        "group_incident_id",
        "timestamp",
        "event_type",
        "severity",
        "cause",
        "degraded_fraction",
        "degraded_members",
        "counts",
    ],
    "properties": {
        "schema_version": {"type": "string"},
        "group_id": {"type": "string"},
        "group_incident_id": {"type": "string"},
        "timestamp": {"type": "number"},
        "event_type": {"type": "string"},
        "severity": {"type": "string"},
        "cause": {"type": "string"},
        "degraded_fraction": {"type": "number"},
        "degraded_members": {"type": "array", "items": {"type": "string"}},
        "counts": {
            "type": "object",
            "required": ["members_total", "members_degraded"],
            "properties": {
                "members_total": {"type": "integer"},
                "members_degraded": {"type": "integer"},
            },
        },
    },
}
